### ISSUE TITLE
No unicode support

### ISSUE THREAD

**Issue by sertys3** [infinitnet/content-update-scheduler#10]
I have tried using this plugin for creating a scheduled post update for an Elementor page. It fails miserable on the first step though as the post meta is copied with escaped slashes and Elementor uses \uXXXX escaping for non-latin characters(e.g. unicode). This breaks the cloned post to begin with. Am I missing something?

Regards,
Daniel

**Comment by infinitnet** [comment]
This should be fixed in https://github.com/infinitnet/content-update-scheduler/commit/41f964367f79cf09b79cd966e532bbcb671a0163
