### ISSUE TITLE
Update messes up custom field contents

### ISSUE THREAD

**Issue by pff729** [infinitnet/content-update-scheduler#11]
I'm using the Code Embed plugin (https://github.com/dartiss/code-embed) to insert custom JS code with the help of custom fields into one of my pages which I try to update with the Content Update Scheduler. But when the post is updated, the content of the custom field is messed up. the CUS removes the <script> tags from the beginning and end of the code snippet and also modifies the "_>_" symbol to _gt;_
Can this be fixed in the future?

**Comment by infinitnet** [comment]
Fixed in https://github.com/infinitnet/content-update-scheduler/commit/d26b46ba1c79deb9c6d3cbb1d4051e67459f287a

**Comment by pff729** [comment]
Thanks for the rapid fast fix, I updated to version 2.3.5 but the issue stayed the same.
A strange thing is that if I manually trigger the update of the page to the new version than everything is fine. This custom field messing up only happens if it auto updates at the scheduled time.
